# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vlăduț Gheorghe
title: IT Operations Specialist
email: brett.h@email.co.uk
website: https://www.linkedin.com/in/vngheorghe/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  rzr19
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: vladut.ng
# flickr_username: jekyll
instagram_username: vladut.ng
linkedin_username: vngheorghe
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:

#- title: itsgoingto.be
# icon: fas fa-globe
# url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/hello.png
about_content: | # this will include new lines to allow paragraphs
  Hello. I am a highly adaptable and self-taught IT Operations Specialist from Cluj-Napoca. 
  I have 8+ years of work experience that taught me <mark>patience</mark>, <mark>collaboration</mark>, <mark>humbleness</mark> and <mark>the bigger picture</mark>.
  The positions I have covered so far ranged from service desk and technical support to system administration and SAP software development.

  My hands-on knowledge revolves around app support, with an emphasis on servers and containers, SAP ECC/PO/Solman, Oracle/MsSQL/MySQL, Docker, Azure, ServiceNow, and many Linux runtime tools.
  I have skills for light development/debugging in ABAP and Java plus a ton of know-how for automation in <mark>bash</mark>, <mark>PL/SQL</mark>, python and Ansible.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Endpoint Protector
        link: https://www.cososys.com/
        # link_text: boringcompany.com
        sub_title: Linux Technical Support
        caption: 2014 - 2015
        description: | # this will include new lines to allow paragraphs
          Support via phone, email, JIRA, OTRS tickets for US/EMEA customers and sales leads.
          Command line work and scripts to troubleshoot Ubuntu LTS servers running php and mysqld.
          App support including installations and configurations of security policies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
    - title: Other certifications and/or  courses I attended
      dates: 2014 - present
      description: | # this will include new lines to allow paragraphs
        AZ-104 Azure Cloud Administrator (2020)
        BIT400 SAP Process Integration (2018)
        LPIC-2 Linux Certified Engineer (2017)
        E2E100 SAP Root Cause Analysis (2016)
        ITILv3 Foundations Certificate (2016)
        Cambridge English Advanced C1 (2014)
      title: Babeș-Bolyai University
      caption: 2014 - 2017
      sub_title: BSc in Business Information Systems (attended)
      description: | # this will include new lines to allow paragraphs
        Got exposure to all the basic technologies and more.
      title: Babeș-Bolyai University
      caption: 2010 - 2013
      sub_title: BSc in Psychology
      description: | # this will include new lines to allow paragraphs
        Graduated with a paper graded 10 on team performance in organisational psychology.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in technology, some of my other interests and hobbies are:
      - Working out
      - Reading books
      - Photo editing
      - reddit and e-communities

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
